repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Specify a version of black that is known to work with click
    hooks:
    -   id: black
        language_version: python3.12 # Ensure this is the correct version
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--ignore=E501,E203,W503,E402"] # E501: line too long, E203: whitespace before ':', W503: line break before binary operator
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports