output_filename: "data/playground.csv"
nparticles: 2
dim: 1 # do not change this in this yaml
nsamples: 262144 # 2^12
nchains: 8
eta: 0.1
training_cycles: 100
mcmc_alg: "m"
optimizer: "sr"
batch_size: 300
detailed: true
nqs_type: "rbm"
backend: "jax"
seed: 42
save_positions: true
particle: "fermion_polarized" # do not change this in this yaml
correlation: "none"
interaction_type: "gaussian" # do not change this in this yaml
latent_dim: 10
sigma_0: 0.5
omega: 1.0 # do not change this in this yaml
v_0: 0.0
base_layer_sizes:
  ffnn: [9, 7, 3, 1]
  ds: 
    S0: [14, 9, 7, 5, 3]
    S1: [7, 5, 3, 1] # first node is latent dim, last node always 1
activations:
  ffnn: ["gelu", "elu", "gelu", "linear"]
  ds: 
    S0: ["gelu", "elu", "gelu", "elu", "gelu", "elu"]
    S1: ["gelu", "elu", "gelu", "linear"]
nhidden: 6
