output_filename: "/Users/orpheus/Documents/Masters/NeuralQuantumState/data/fermion_polarized/"
nparticles: 2
dim: 1 # do not change this in this yaml
nsamples: 2048 #2097152 #2097152 #16777216 # 2^18
nchains: 8 # disclaimer! see if deepset will also be fast with 8 chains
eta: 0.00001 #02467038091177851 #0.008
training_cycles: 1500
mcmc_alg: "m"
optimizer: "sr"
batch_size: 1000
detailed: true
nqs_type: "vmc"
backend: "jax"
seed: 42
save_positions: False
particle: "fermion_polarized" # do not change this in this yaml
correlation: "none" # None or j or pj
interaction_type: "gaussian" # do not change this in this yaml

sigma_0: 0.5
omega: 1.0 # do not change this in this yaml
v_0: 0
pretrain: True
latent_dim: 10
base_layer_sizes:
  dsffn: 
    S0: [9, 7, 5, 3] # [7, 5, 3] # [14, 9, 7, 5, 3]  [7, 5, 3] #
    S1: [3, 1] # [3, 1] #[7, 5, 3, 1] #[3, 1] #[7, 5, 3, 1] # first node is latent dim, last node always 1
activations:
  dsffn: 
    S0: ["gelu","gelu", "gelu", "gelu", "gelu"]
    S1: ["gelu", "linear"]
nhidden: 5
