wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701352540.76256
    t:
      1:
      - 12
      - 53
      - 55
      2:
      - 12
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
nsamples:
  desc: null
  value: 32768
eta:
  desc: null
  value: 0.1
training_cycles:
  desc: null
  value: 10000
mcmc_alg:
  desc: null
  value: m
optimizer:
  desc: null
  value: adam
batch_size:
  desc: null
  value: 1000
detailed:
  desc: null
  value: true
wf_type:
  desc: null
  value: ffnn
sr:
  desc: null
  value: false
scale:
  desc: null
  value: 1
tune:
  desc: null
  value: false
gamma:
  desc: null
  value: 0
