wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701441982.147674
    t:
      1:
      - 12
      - 53
      - 55
      2:
      - 12
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
nsamples:
  desc: null
  value: 1024
eta:
  desc: null
  value: 0.1
training_cycles:
  desc: null
  value: 10000
batch_proportion:
  desc: null
  value: 0.1
mcmc_alg:
  desc: null
  value: m
optimizer:
  desc: null
  value: adam
sr:
  desc: null
  value: false
scale:
  desc: null
  value: 1
tune:
  desc: null
  value: false
clip:
  desc: null
  value: 0
gamma:
  desc: null
  value: 0
num_layers:
  desc: null
  value: 3
